import AppKit
import Foundation
import SwiftData
import Observation
import SwiftUI
import LociiGhostCore

/// Top-level @Observable state for the SwiftUI app.
///
/// Holds the long-lived `DaemonClient` actor and surfaces device/connection
/// state for views. Views observe individual fields — SwiftUI will only
/// re-render the parts that change.
@MainActor
@Observable
final class AppState {
    // MARK: - Connection
    enum DaemonStatus: Equatable {
        case stopped
        case starting
        case running
        case failed(String)

        var label: String {
            switch self {
            case .stopped: return "Stopped"
            case .starting: return "Starting…"
            case .running: return "Running"
            case .failed(let s): return "Failed: \(s)"
            }
        }
    }

    var daemonStatus: DaemonStatus = .stopped
    var daemonVersion: String = ""
    var lastError: String?

    // MARK: - Devices
    var devices: [DeviceVM] = []
    var selectedUDID: String?

    // MARK: - Pending teleport / stops
    /// Ordered list of points the user has staged on the map but not yet
    /// committed. Each click on the map (or each successful search) appends
    /// a new stop. Navigate consumes the entire list as an in-order
    /// multi-waypoint route. Teleport uses the *last* stop only.
    // didSet on @Observable array properties does not fire reliably for
    // in-place mutations (`.append`, `.remove(at:)`); the @Observable
    // macro routes those through `_modify` which skips willSet/didSet.
    // The view layer drives `schedulePreviewRefresh()` via `.onChange`
    // instead — see MainView's bootstrap modifiers.
    var pendingStops: [Coordinate] = []
    var lastTeleportedAt: Date?

    // MARK: - Route preview
    /// Polyline shown on the map while the user is still planning the
    /// trip — i.e., before pressing Navigate. Mirrors what the active
    /// route will look like, so the user sees the consequence of toggling
    /// straight-line mode or adding/removing stops without committing.
    var previewRoute: [Coordinate] = []
    /// Mirrors `useStraightLine` at the moment the preview was last
    /// computed, so the map renderer can pick the right style even if
    /// the user toggles the preference between refreshes.
    var previewIsStraightLine: Bool = false
    /// What the iPhone is currently *simulating* — i.e., where Maps and
    /// other apps on the phone think they are. nil means we are not
    /// simulating; phone is reporting its real GPS. Persisted via
    /// `didSet` so a relaunch can repaint the blue dot before the
    /// daemon's first state push lands.
    var simulatedLocation: Coordinate? {
        didSet { persistLastSimulated() }
    }

    // MARK: - Navigation
    /// Travel profile + matching default speed for the next Navigate click.
    /// `didSet` persists immediately so the user's last choice survives
    /// a relaunch.
    var travelProfile: TravelProfile = .driving {
        didSet { persistRoutingPrefs() }
    }
    /// Override speed in m/s. nil means "use the profile default".
    var customSpeedMps: Double? {
        didSet { persistRoutingPrefs() }
    }
    /// When true, the next Navigate skips OSRM and walks the iPhone
    /// straight-line between consecutive stops. Cannot be toggled mid-
    /// navigation — the route was already computed; if you want to
    /// switch, Stop, flip this, then Navigate again.
    /// (Same `_modify` caveat as `pendingStops` — preview refresh is
    /// driven from the view layer via `.onChange`.)
    var useStraightLine: Bool = false
    /// How many times to walk the route on the next Navigate. 1 = a
    /// single trip; 2+ closes the route into a loop and repeats the
    /// closed loop N times. Persists like `travelProfile` so a
    /// previously-set value survives clearing/restoring stops.
    var routeLaps: Int = 1
    /// Live navigation snapshot from the daemon. Updated via
    /// `event.position_update` and `event.state_changed`. Becomes nil when
    /// navigation finishes (reached / stopped) but `activeRoute` keeps the
    /// last route + destination visible on the map.
    var navigation: NavigationVM?

    /// The most recent navigation's full route polyline. Persists across
    /// pause / stop / arrival so the user can still see where they were
    /// going. Cleared explicitly by Restore, by starting a new navigation,
    /// or by Teleport.
    var activeRoute: [Coordinate]?
    /// Last point of `activeRoute`, kept as a separate field so the map can
    /// draw the destination flag without scanning the route every refresh.
    var activeDestination: Coordinate?
    /// True when `activeRoute` was generated by the daemon's straight-line
    /// mode (no OSRM lookup). The map renderer reads this to draw the
    /// polyline dashed instead of solid, so the visual style itself
    /// confirms the mode.
    var activeRouteIsStraightLine: Bool = false

    // MARK: - Map fly requests
    /// One-shot map-recenter request from search results, "Show on map"
    /// buttons, etc. Each new request gets a fresh UUID; the map view's
    /// coordinator remembers the last id it serviced and ignores
    /// duplicates so updateNSView() stays idempotent.
    var pendingMapFly: MapFlyRequest?

    // MARK: - Mac proxy location
    let macLocation = LocationProxyService()

    // MARK: - Privilege state
    /// True if the connected daemon is running as root (set after a
    /// successful daemon.info call). False means we'll fail at the
    /// utun step on Connect; the GUI should surface an admin prompt.
    /// nil = haven't asked yet.
    var daemonIsRoot: Bool?
    /// Sticky flag set when a Connect attempt fails with TUNNEL_FAILED.
    /// Lets the BottomBar / banner offer "Authenticate as admin" until
    /// the next successful elevation or Restore.
    var needsAdminElevation: Bool = false
    /// True while `requestAdminElevation()` is in flight — the auth
    /// dialog is up or the daemon is still spawning.
    var isElevating: Bool = false

    // MARK: - WiFi pairing + IP-direct connect (Phase 4.5)
    /// Latest set of iPhones the daemon found on the LAN via mDNS or
    /// /24 TCP scan. `nil` until `discoverWiFi()` runs once. Each entry
    /// is `(ip, port, name, method)` — UDID is unknown until the actual
    /// pair-verify in `connectWiFiByIP` resolves it.
    var wifiCandidates: [WiFiCandidate]?
    /// True while a `wifi.repair`, `wifi.discover`, or `wifi.connect_ip`
    /// RPC is in flight, so the UI can disable buttons + show spinners.
    var isPairingForWiFi: Bool = false
    var isDiscoveringWiFi: Bool = false
    var isConnectingWiFiByIP: Bool = false
    /// Live two-stage pair-progress, populated from
    /// `event.wifi_pair_progress` while `pairForWiFi()` runs. nil
    /// outside of an active pair operation. The GUI uses `.fraction`
    /// for a determinate ProgressView and `.message` for the
    /// "Step 1/2: tap Trust on iPhone" label.
    var pairProgress: PairProgress?
    /// When non-nil, the WiFi-connect selection sheet is open for the
    /// given device. Set by `openWiFiConnectFlow(udid:)` (which the
    /// Connect-via-WiFi button hooks into); the sheet itself owns the
    /// dismiss and clears this back to nil. Letting AppState own the
    /// presentation makes auto-discover-on-open trivial: the sheet
    /// kicks off `discoverWiFi()` on appear and the existing
    /// observable bindings paint the result.
    var wifiConnectSheet: WiFiConnectSheetTarget?

    // MARK: - Phone control (Phase 5.2)
    /// LAN URL + PIN for the daemon's phone-control HTTP server.
    /// Populated by `fetchPhoneControlInfo()`; sheet renders these
    /// for the user to type into their phone browser. The endpoint
    /// is localhost-only on the daemon side, so this info is never
    /// exposed to the LAN — only the desktop GUI can fetch it.
    var phoneControlInfo: PhoneControlInfo?
    var isLoadingPhoneInfo: Bool = false
    /// Drives the phone-control sheet presentation.
    var showPhoneControlSheet: Bool = false

    // MARK: - Movement modes (Phase 3)
    /// Latest snapshot from a `location.random_walk` session, populated
    /// from `event.position_update` / `event.state_changed` notifications.
    /// nil means no walker is running.
    var randomWalk: RandomWalkVM?
    /// Latest snapshot from a `location.joystick` session.
    var joystick: JoystickVM?

    /// Live preview of the random-walk bounds while the user is still
    /// configuring the panel. The map renders a translucent disc using
    /// these values so the user can see exactly which area the iPhone
    /// will wander before they press Start. Cleared as soon as the
    /// panel goes away, or once a real walker is running (the actual
    /// motion is its own visual story).
    var randomWalkPreviewCenter: Coordinate?
    var randomWalkPreviewRadiusM: Double?

    // MARK: - Internals
    private var lifecycle: DaemonLifecycle?
    private var client: DaemonClient?
    private var eventTask: Task<Void, Never>?
    private var previewTask: Task<Void, Never>?

    // MARK: - Persistence (Phase 5.2 — SwiftData)

    /// SwiftData context, attached at app launch by LociiGhostApp.
    /// nil before attach (early bootstrap calls just no-op the
    /// persistence read/writes; the in-memory defaults still work).
    private var modelContext: ModelContext?
    private var preferences: AppPreferences?

    /// Called from LociiGhostApp.task right before bootstrap so we
    /// can hydrate AppState from disk before the daemon connects.
    /// Idempotent — safe to call again on a hot reload.
    func attachModelContext(_ ctx: ModelContext) {
        modelContext = ctx
        let prefs = AppPreferences.fetchOrCreate(ctx)
        preferences = prefs
        // Hydrate transient AppState fields from the persisted
        // record so the UI repaints with the user's last choices
        // before the daemon is even up.
        if let raw = TravelProfile(rawValue: prefs.travelProfileRaw) {
            travelProfile = raw
        }
        customSpeedMps = prefs.customSpeedMps
        if let lat = prefs.lastSimulatedLat,
           let lng = prefs.lastSimulatedLng {
            simulatedLocation = Coordinate(lat: lat, lng: lng)
        }
    }

    /// The last persisted map camera (or nil if we never saved one).
    /// MapContainerView reads this on first appear so the map opens
    /// where the user left it.
    var savedMapCamera: (center: Coordinate, spanMeters: Double)? {
        guard let p = preferences,
              let lat = p.mapCenterLat,
              let lng = p.mapCenterLng,
              let span = p.mapSpanMeters
        else { return nil }
        return (Coordinate(lat: lat, lng: lng), span)
    }

    /// Called by MapContainerView when the user pans / zooms. Throttled
    /// upstream so we don't write to disk on every pixel of movement.
    func saveMapCamera(centerLat: Double, centerLng: Double, spanMeters: Double) {
        guard let p = preferences else { return }
        p.mapCenterLat = centerLat
        p.mapCenterLng = centerLng
        p.mapSpanMeters = spanMeters
        try? modelContext?.save()
    }

    /// Persist whatever the SwiftUI state currently is. Called from
    /// the property accessors that already mutate AppState — keeps
    /// preference disk-state aligned without us scattering save calls
    /// over every random place that touches travelProfile etc.
    func persistRoutingPrefs() {
        guard let p = preferences else { return }
        p.travelProfileRaw = travelProfile.rawValue
        p.customSpeedMps = customSpeedMps
        try? modelContext?.save()
    }
    func persistLastSimulated() {
        guard let p = preferences else { return }
        p.lastSimulatedLat = simulatedLocation?.lat
        p.lastSimulatedLng = simulatedLocation?.lng
        try? modelContext?.save()
    }

    // MARK: - Bootstrap

    func bootstrap() async {
        guard daemonStatus == .stopped else { return }
        daemonStatus = .starting

        // Stage the daemon out of `~/Documents` (TCC-protected on
        // macOS 15+) before we try to spawn it. This is a fast no-op
        // if the staged copy is already up to date.
        do {
            try await DaemonStaging.ensureStaged()
        } catch {
            let msg = "Daemon staging failed: \(error.localizedDescription)"
            lastError = msg
            daemonStatus = .failed(msg)
            return
        }

        // Fire off the Mac-location request in parallel with daemon bringup.
        // The fix typically lands within a second; if the user hasn't
        // granted permission yet they'll see the system prompt now.
        macLocation.requestPermissionAndFetch()

        let lifecycle = DaemonLifecycle()
        self.lifecycle = lifecycle
        do {
            try lifecycle.start()
            // Wait for the socket to appear (daemon binds it on startup).
            let path = LociiGhostPaths.socketPath
            let started = await Self.waitForSocket(path: path, timeout: 5.0)
            guard started else {
                daemonStatus = .failed("daemon socket did not appear")
                return
            }

            let client = DaemonClient(socketPath: path)
            try await client.connect()
            self.client = client

            // Confirm liveness and learn the version.
            struct Pong: Decodable { let pong: Bool; let version: String }
            let pong: Pong = try await client.call("ping")
            daemonVersion = pong.version
            daemonStatus = .running

            // ping just told us a live daemon version. If it matches
            // what this build expects, *unconditionally* clear the
            // "needs admin" sticky flag — we know the kill-and-restart
            // (or first-time spawn) succeeded and the daemon picked up
            // current bytecode. Without this, the banner can latch on
            // forever because the only previous clear point was tied to
            // a successful Connect, which the user can't reach until
            // the banner is gone in the first place.
            if pong.version == AppState.expectedDaemonVersion {
                needsAdminElevation = false
            }

            // Now that we have a live client, ask the daemon whether
            // it's running as root and matches the bundled-source
            // version. Either signal flips on the admin banner so the
            // user has a one-click path to fix it.
            await refreshDaemonPrivilegeAfterConnect()

            startEventLoop(client: client)

            await refreshDevices()
        } catch {
            daemonStatus = .failed(String(describing: error))
        }
    }

    func teardown() async {
        eventTask?.cancel()
        eventTask = nil

        // Only shut the daemon down if WE spawned it. If we attached to an
        // already-running (typically sudo-launched) daemon, leave it alone
        // so the next app launch can re-attach without re-prompting for
        // the admin password — and so the in-memory device caches survive
        // an app close+reopen cycle (the on-disk cache is the safety net
        // for harder restarts where the daemon does die).
        let ownsDaemon = lifecycle?.attachedToExisting == false
        NSLog("LociiGhost.teardown: ownsDaemon=%@ (attachedToExisting=%@)",
              ownsDaemon ? "true" : "false",
              (lifecycle?.attachedToExisting ?? false) ? "true" : "false")
        if let client {
            if ownsDaemon {
                _ = try? await client.callRaw("daemon.shutdown")
            }
            await client.disconnect()
        }
        client = nil

        lifecycle?.stop()
        lifecycle = nil
        daemonStatus = .stopped
    }

    /// Terminate the app process. Same effect as Cmd-Q. Triggers the
    /// app delegate's `applicationWillTerminate` which calls `teardown()`.
    func quitApp() {
        NSApp.terminate(nil)
    }

    // MARK: - Devices

    func refreshDevices() async {
        guard let client else { return }
        do {
            let raw: AnyCodable = try await client.callRaw("device.list")
            let data = try JSONEncoder().encode(raw)
            let list = try JSONDecoder().decode([DeviceVM].self, from: data)
            self.devices = list
            // Auto-select the first connected device, or the only device.
            if selectedUDID == nil {
                selectedUDID = list.first(where: { $0.connected })?.udid
                    ?? list.first?.udid
            }
        } catch {
            lastError = String(describing: error)
        }
    }

    func connect(udid: String, preferWiFi: Bool = false) async {
        guard let client else { return }
        do {
            var params: [String: AnyCodable] = ["udid": AnyCodable(udid)]
            if preferWiFi {
                params["prefer_wifi"] = AnyCodable(true)
            }
            _ = try await client.callRaw("device.connect", params: params)
            await refreshDevices()
            // Successful Connect → tunnel built → daemon clearly has
            // enough privilege. Drop both "needs admin" signals so the
            // banner cannot reappear from a stale daemon.info that
            // never got a chance to update daemonIsRoot. (Earlier
            // versions cleared only `needsAdminElevation`, which left
            // daemonIsRoot==Optional(false) sticky from the original
            // user-mode bootstrap and made the banner re-show forever.)
            needsAdminElevation = false
            daemonIsRoot = true
        } catch {
            lastError = String(describing: error)
            // -32004 == TUNNEL_FAILED. On Apple Silicon the only thing
            // that fails this on USB is "daemon isn't root", because
            // utun creation in pytun_pmd3 needs CAP_NET_ADMIN-equivalent.
            if let rpc = error as? RPCError, rpc.code == -32004 {
                needsAdminElevation = true
            }
        }
    }

    func disconnect(udid: String) async {
        guard let client else { return }
        do {
            _ = try await client.callRaw("device.disconnect", params: ["udid": AnyCodable(udid)])
            await refreshDevices()
        } catch {
            lastError = String(describing: error)
        }
    }

    // MARK: - WiFi pairing + IP-direct connect

    /// Run the daemon's one-time `wifi.repair` ritual: USB autopair →
    /// CoreDeviceTunnelProxy → RSD → `create_core_device_tunnel_service_using_rsd(autopair=True)`
    /// which writes a fresh `~/.pymobiledevice3/remote_<UDID>.plist`.
    /// Two iOS Trust prompts appear during this; user must tap Trust on
    /// each. After this completes once, `connectWiFiByIP` works without
    /// the cable indefinitely.
    func pairForWiFi(udid: String? = nil) async {
        guard let client else { return }
        guard !isPairingForWiFi else { return }
        isPairingForWiFi = true
        defer { isPairingForWiFi = false }
        do {
            var params: [String: AnyCodable] = [:]
            if let udid { params["udid"] = AnyCodable(udid) }
            _ = try await client.callRaw("wifi.repair", params: params)
            lastError = nil
            // Pairing record is fresh — kick off discovery so the
            // newly-pairable iPhone appears in the WiFi list.
            await discoverWiFi()
        } catch {
            lastError = String(describing: error)
        }
    }

    /// Browse the LAN for paired iPhones (mDNS first, /24 TCP scan
    /// fallback). Stores results in `wifiCandidates` for the UI.
    func discoverWiFi() async {
        guard let client else { return }
        guard !isDiscoveringWiFi else { return }
        isDiscoveringWiFi = true
        defer { isDiscoveringWiFi = false }
        do {
            let raw: [WiFiCandidate] = try await client.call(
                "wifi.discover",
                params: ["scan_subnet": AnyCodable(true)]
            )
            wifiCandidates = raw
        } catch {
            wifiCandidates = []
            lastError = String(describing: error)
        }
    }

    /// Open the WiFi-connect selection sheet for `udid`. This is what
    /// the device row's "Connect via WiFi" button calls — instead of
    /// firing the legacy Bonjour-only connect path that returns a
    /// service-map-stripped RSD on iOS 26, the sheet auto-discovers
    /// LAN-reachable iPhones, lists them, and routes the user's pick
    /// through `connectWiFiByIP` (which opens the FULL RSD). If
    /// discovery returns nothing the sheet falls back to a manual
    /// IP entry field.
    func openWiFiConnectFlow(udid: String) {
        wifiConnectSheet = WiFiConnectSheetTarget(udid: udid)
        // Kick off a fresh discover so the sheet's list is current.
        // Fire-and-forget — the sheet's body re-renders as soon as
        // `wifiCandidates` updates.
        Task { await self.discoverWiFi() }
    }

    /// Connect to an iPhone discovered by `discoverWiFi()` (or any
    /// IP+port the user typed in manually). Uses the daemon's
    /// `wifi.connect_ip` which goes through
    /// `create_core_device_tunnel_service_using_remotepairing` directly,
    /// bypassing Bonjour at connect time and yielding the FULL RSD
    /// (with `dtservicehub`) — i.e. WiFi-only DVT location simulation
    /// works without a USB cable.
    ///
    /// On `-32004 TUNNEL_FAILED` (which on this path almost always
    /// means "iPhone moved to a different IP since the last
    /// discover"), kicks off a fresh `discoverWiFi()` automatically.
    /// The user sees the candidate list refresh and can click again
    /// without thinking about IP rotation.
    func connectWiFiByIP(ip: String, port: Int = 49152, udid: String? = nil) async {
        guard let client else { return }
        guard !isConnectingWiFiByIP else { return }
        isConnectingWiFiByIP = true
        defer { isConnectingWiFiByIP = false }
        do {
            var params: [String: AnyCodable] = [
                "ip": AnyCodable(ip),
                "port": AnyCodable(port),
            ]
            if let udid { params["udid"] = AnyCodable(udid) }
            _ = try await client.callRaw("wifi.connect_ip", params: params)
            lastError = nil
            await refreshDevices()
            // Successful Connect → full developer tunnel up → daemon is
            // exercising root utun, so admin signals are stale-clear.
            needsAdminElevation = false
            daemonIsRoot = true
        } catch {
            lastError = String(describing: error)
            if let rpc = error as? RPCError, rpc.code == -32004 {
                needsAdminElevation = true
            }
            // Tunnel failures on this path strongly correlate with the
            // iPhone having taken a new DHCP lease since we last
            // discovered. Fire-and-forget a refresh so the candidate
            // list is current next time the user clicks.
            Task { await self.discoverWiFi() }
        }
    }

    // MARK: - Phone control

    /// Candidate ports we walk when looking for the daemon's phone-
    /// control HTTP server. Must match `PORT_CANDIDATES` in
    /// `Daemon/lociighostd/http_server.py` — the daemon picks the
    /// first free one at startup, and this list is how we find
    /// where it actually landed without a separate RPC roundtrip.
    private static let phoneControlPorts: [Int] = [8779, 8780, 8781, 8788, 8789, 8800]

    /// Fetch the LAN URL + 6-digit PIN from the daemon's phone-control
    /// HTTP server. Walks the candidate-port list (the daemon may
    /// have fallen back from 8779 to 8780 etc. if a port was busy)
    /// and returns the first one that answers. The endpoint is
    /// localhost-only on the daemon, so we hit `127.0.0.1` directly
    /// over HTTP instead of going through our JSON-RPC socket.
    func fetchPhoneControlInfo() async {
        guard !isLoadingPhoneInfo else { return }
        isLoadingPhoneInfo = true
        defer { isLoadingPhoneInfo = false }
        for port in Self.phoneControlPorts {
            guard let url = URL(string: "http://127.0.0.1:\(port)/api/phone/info")
            else { continue }
            var req = URLRequest(url: url)
            req.timeoutInterval = 1.5
            do {
                let (data, response) = try await URLSession.shared.data(for: req)
                guard let http = response as? HTTPURLResponse, http.statusCode == 200
                else { continue }
                phoneControlInfo = try JSONDecoder().decode(PhoneControlInfo.self, from: data)
                return
            } catch {
                continue
            }
        }
        phoneControlInfo = nil
        lastError = "Phone control HTTP server isn't reachable on any candidate port (\(Self.phoneControlPorts.map(String.init).joined(separator: ", ")))."
    }

    /// Generate a fresh PIN + token. Invalidates any phone tab that
    /// was previously authed against the old token.
    func rotatePhoneControlPIN() async {
        // Use whichever port we already discovered — falls back to
        // re-walking the candidate list if we don't have one cached.
        let port: Int
        if let info = phoneControlInfo { port = info.port }
        else {
            await fetchPhoneControlInfo()
            guard let info = phoneControlInfo else { return }
            port = info.port
        }
        guard let url = URL(string: "http://127.0.0.1:\(port)/api/phone/rotate") else { return }
        var req = URLRequest(url: url)
        req.httpMethod = "POST"
        do {
            _ = try await URLSession.shared.data(for: req)
            await fetchPhoneControlInfo()
        } catch {
            lastError = String(describing: error)
        }
    }

    /// Open the phone-control sheet from anywhere in the UI. Auto-
    /// fetches info on appear so the sheet always shows current state.
    func openPhoneControlSheet() {
        showPhoneControlSheet = true
        Task { await fetchPhoneControlInfo() }
    }

    /// Ask the daemon to surface the Developer Mode toggle in iPhone Settings.
    /// Returns the next-step strings the daemon sent so the UI can show them.
    func revealDeveloperMode(udid: String) async -> [String] {
        guard let client else { return [] }
        struct Reply: Decodable { let ok: Bool; let next_steps: [String] }
        do {
            let reply: Reply = try await client.call("device.reveal_developer_mode",
                                                     params: ["udid": AnyCodable(udid)])
            return reply.next_steps
        } catch {
            lastError = String(describing: error)
            return []
        }
    }

    // MARK: - Teleport

    func teleport(udid: String, lat: Double, lng: Double) async {
        guard let client else { return }
        do {
            _ = try await client.callRaw("location.teleport", params: [
                "udid": AnyCodable(udid),
                "lat":  AnyCodable(lat),
                "lng":  AnyCodable(lng),
            ])
            lastTeleportedAt = Date()
            simulatedLocation = Coordinate(lat: lat, lng: lng)
            pendingStops = []
            navigation = nil
            // Teleport replaces the trip — no road context to keep.
            activeRoute = nil
            activeDestination = nil
            activeRouteIsStraightLine = false
        } catch {
            lastError = String(describing: error)
        }
    }

    /// Plan a route from "current" through `stops` in order and start
    /// the iPhone moving along it at `speed`. With one stop this is a
    /// simple A→B navigation; with multiple it visits each stop in order
    /// before reaching the final destination.
    ///
    /// Origin is the current simulated location if we have one (chained
    /// navigation), else the Mac proxy fix.
    func navigate(udid: String, through stops: [Coordinate], profile: TravelProfile, speed: Double) async {
        guard let client else { return }
        guard let origin = navigationOrigin() else {
            lastError = "Need a starting location: enable Mac location or teleport first."
            return
        }
        guard !stops.isEmpty else { return }

        let waypoints = [origin] + stops
        // AnyCodable's encoder only walks the recursive shapes it knows
        // about: [AnyCodable] and [String: AnyCodable]. A bare
        // [[String: AnyCodable]] falls into its `default` branch and
        // throws "Unsupported AnyCodable value". Wrap each dict in
        // AnyCodable so the outer array becomes [AnyCodable].
        let stopsParam: [AnyCodable] = waypoints.map { c in
            AnyCodable([
                "lat": AnyCodable(c.lat),
                "lng": AnyCodable(c.lng),
            ])
        }

        do {
            struct Reply: Decodable {
                struct Route: Decodable {
                    let coordinates: [Coord]
                    let distance_m: Double
                    let duration_s: Double
                    let profile: String
                }
                struct Coord: Decodable { let lat: Double; let lng: Double }
                let route: Route
                let speed_mps: Double
            }
            let reply: Reply = try await client.call("location.navigate", params: [
                "udid":     AnyCodable(udid),
                "stops":    AnyCodable(stopsParam),
                "profile":  AnyCodable(profile.rawValue),
                "speed_mps": AnyCodable(speed),
                "straight_line": AnyCodable(useStraightLine),
                "laps":     AnyCodable(max(1, routeLaps)),
            ])
            let coords = reply.route.coordinates.map { Coordinate(lat: $0.lat, lng: $0.lng) }
            navigation = NavigationVM(
                state: .moving,
                profile: profile,
                speedMps: reply.speed_mps,
                routeCoordinates: coords,
                distanceM: reply.route.distance_m,
                etaSeconds: reply.route.duration_s,
                currentLocation: origin,
                progress: 0,
                laps: max(1, routeLaps)
            )
            // Pin the route + destination on the map. These outlive the
            // live `navigation` state machine so the user can still see
            // where they were going after Pause / Stop / Arrived.
            activeRoute = coords
            activeDestination = stops.last ?? coords.last
            activeRouteIsStraightLine = useStraightLine
            simulatedLocation = origin
            pendingStops = []
        } catch {
            lastError = String(describing: error)
        }
    }

    func pauseNavigation(udid: String) async {
        guard let client else { return }
        _ = try? await client.callRaw("location.pause", params: ["udid": AnyCodable(udid)])
        if var nav = navigation {
            nav.state = .paused
            navigation = nav
        }
    }

    func resumeNavigation(udid: String) async {
        guard let client else { return }
        _ = try? await client.callRaw("location.resume", params: ["udid": AnyCodable(udid)])
        if var nav = navigation {
            nav.state = .moving
            navigation = nav
        }
    }

    func stopNavigation(udid: String) async {
        guard let client else { return }
        _ = try? await client.callRaw("location.stop", params: ["udid": AnyCodable(udid)])
        navigation = nil
    }

    // ------------------------------------------------------------------
    // Random walk
    // ------------------------------------------------------------------

    /// Start a random-walk simulation centred on `center`, drifting up to
    /// `radiusM` metres away at speeds within the given band (m/s).
    func startRandomWalk(udid: String,
                         center: Coordinate,
                         radiusM: Double,
                         minSpeedMps: Double,
                         maxSpeedMps: Double) async {
        guard let client else { return }
        do {
            struct StartReply: Decodable {
                struct Coord: Decodable { let lat: Double; let lng: Double }
                let planned_path: [Coord]?
            }
            let reply: StartReply = try await client.call("location.random_walk", params: [
                "udid":          AnyCodable(udid),
                "center_lat":    AnyCodable(center.lat),
                "center_lng":    AnyCodable(center.lng),
                "radius_m":      AnyCodable(radiusM),
                "min_speed_mps": AnyCodable(minSpeedMps),
                "max_speed_mps": AnyCodable(maxSpeedMps),
            ])
            randomWalk = RandomWalkVM(
                center: center,
                radiusM: radiusM,
                current: center,
                speedMps: 0,
                distanceTraveledM: 0,
                isMoving: true,
                plannedPath: (reply.planned_path ?? []).map {
                    Coordinate(lat: $0.lat, lng: $0.lng)
                }
            )
            // Drop other movement modes from the local view so the UI
            // doesn't render stale state from a previous mode.
            navigation = nil
            joystick = nil
            simulatedLocation = center
        } catch {
            lastError = String(describing: error)
        }
    }

    func stopRandomWalk(udid: String) async {
        guard let client else { return }
        _ = try? await client.callRaw("location.stop", params: ["udid": AnyCodable(udid)])
        randomWalk = nil
    }

    // ------------------------------------------------------------------
    // Joystick
    // ------------------------------------------------------------------

    /// Begin a joystick session. Origin defaults to the current simulated
    /// (or Mac proxy) location so the first frame the iPhone sees is
    /// "where it already thinks it is", not a sudden teleport.
    func startJoystick(udid: String, origin: Coordinate) async {
        guard let client else { return }
        do {
            _ = try await client.callRaw("location.joystick.start", params: [
                "udid": AnyCodable(udid),
                "lat":  AnyCodable(origin.lat),
                "lng":  AnyCodable(origin.lng),
            ])
            joystick = JoystickVM(
                current: origin,
                headingDeg: 0,
                speedMps: 0,
                isMoving: false
            )
            navigation = nil
            randomWalk = nil
            simulatedLocation = origin
        } catch {
            lastError = String(describing: error)
        }
    }

    /// Push a (heading, speed) update into the active joystick session.
    /// `speedMps == 0` parks the controller — iPhone freezes in place
    /// until the next non-zero update.
    func updateJoystick(udid: String, headingDeg: Double, speedMps: Double) async {
        guard let client else { return }
        _ = try? await client.callRaw("location.joystick.update", params: [
            "udid":        AnyCodable(udid),
            "heading_deg": AnyCodable(headingDeg),
            "speed_mps":   AnyCodable(speedMps),
        ])
        if var js = joystick {
            js.headingDeg = headingDeg
            js.speedMps = speedMps
            js.isMoving = speedMps > 0
            joystick = js
        }
    }

    func stopJoystick(udid: String) async {
        guard let client else { return }
        _ = try? await client.callRaw("location.stop", params: ["udid": AnyCodable(udid)])
        joystick = nil
    }

    func applyNavigationSpeed(udid: String, speedMps: Double) async {
        guard let client else { return }
        _ = try? await client.callRaw("location.apply_speed", params: [
            "udid": AnyCodable(udid),
            "speed_mps": AnyCodable(speedMps),
        ])
        if var nav = navigation {
            nav.speedMps = speedMps
            navigation = nav
        }
    }

    /// Switch travel mode mid-route. The route polyline doesn't change
    /// (it was computed for the original profile), only the speed at
    /// which we walk it. This is the hot-swap from the original LociiGhost.
    func changeNavigationProfile(udid: String, to profile: TravelProfile) async {
        let speed = customSpeedMps ?? profile.defaultSpeedMps
        await applyNavigationSpeed(udid: udid, speedMps: speed)
        if var nav = navigation {
            nav.profile = profile
            navigation = nav
        }
        // Keep the global picker in sync so the next Navigate uses the
        // mode the user just picked.
        travelProfile = profile
    }

    // ------------------------------------------------------------------
    // Admin elevation
    // ------------------------------------------------------------------

    /// Show the macOS admin auth prompt, then bring up a privileged
    /// daemon and reconnect. The user never has to open a terminal —
    /// this is the same dialog Installer.app uses.
    ///
    /// On cancellation we leave the existing (likely unprivileged)
    /// daemon alone so the user can keep using the app's read-only
    /// features (device discovery, Mac-location proxy, etc.).
    func requestAdminElevation() async {
        guard !isElevating else { return }
        isElevating = true
        defer { isElevating = false }

        // Reset privilege state to "unknown" *now*, before we tear
        // anything down. Without this, a stale `daemonIsRoot ==
        // Optional(false)` from the original user-mode bootstrap
        // remains sticky if the post-install daemon.info call fails
        // for any reason (race against daemon startup, transient
        // socket reset, etc.), and the banner stays up forever.
        // nil != false, so the banner is dismissed while we're
        // re-elevating; refreshDaemonPrivilegeAfterConnect will set
        // it to a definite Bool once the new daemon answers.
        daemonIsRoot = nil

        // Tear our current connection down first so we don't try to
        // talk to a daemon that's about to be killed by the bootstrap
        // script.
        eventTask?.cancel()
        eventTask = nil
        if let c = client {
            await c.disconnect()
        }
        client = nil
        // The lifecycle reference belongs to whichever daemon we
        // spawned (or attached to) earlier — drop it without sending
        // shutdown so we don't accidentally restart the kill loop.
        lifecycle?.stop()
        lifecycle = nil
        daemonStatus = .stopped

        // Re-stage the daemon before privilege install so the root
        // daemon picks up any source changes since last launch. Day-
        // to-day fixes (e.g. the QUIC→TCP tunnel switch) only take
        // effect once the daemon is restarted with the new files.
        do {
            try await DaemonStaging.ensureStaged()
        } catch {
            lastError = "Daemon staging failed: \(error.localizedDescription)"
        }

        do {
            try await PrivilegedDaemonInstaller.install()
            needsAdminElevation = false
            lastError = nil
            // Re-bootstrap will see the now-existing privileged socket
            // and attach to it.
            await bootstrap()
            await refreshDevices()
        } catch PrivilegedDaemonInstaller.InstallError.userCancelled {
            // User chose not to authenticate. Restore the basic
            // unprivileged daemon so the app isn't dead in the water.
            await bootstrap()
        } catch {
            lastError = "Admin install failed: \(error.localizedDescription)"
            await bootstrap()
        }
    }

    /// Probe the connected daemon to see if it's running as root, so
    /// the UI knows whether to offer an "Authenticate as admin"
    /// affordance up front rather than waiting for a connect failure.
    /// Also checks the daemon's version: if it's older than the
    /// version bundled with this app build, the daemon process is
    /// running stale in-memory bytecode and we should ask the user
    /// to re-authenticate so the kill-and-restart picks up the new
    /// code.
    private func refreshDaemonPrivilegeAfterConnect() async {
        guard let client else { return }
        struct InfoReply: Decodable {
            let is_root: Bool?
            let version: String?
        }
        guard let reply: InfoReply = try? await client.call("daemon.info") else {
            return
        }
        daemonIsRoot = reply.is_root
        if let liveVersion = reply.version,
           liveVersion != AppState.expectedDaemonVersion {
            // Daemon is alive but its bytecode predates this app
            // build's daemon source. Surface the auth banner; clicking
            // Authenticate will trigger the kill-and-restart flow.
            needsAdminElevation = true
        } else if reply.version == AppState.expectedDaemonVersion {
            // Versions match — the previous "stale daemon" condition
            // (if any) has been resolved by the kill-and-restart flow.
            // Without this clear, `needsAdminElevation` stays sticky-
            // true forever and the banner reappears on every connect
            // even though the daemon is already up to date.
            needsAdminElevation = false
        }
    }

    /// Bumped every time the daemon source breaks ABI or behaviour in
    /// a way that requires an in-place restart. Must match the
    /// `__version__` in `Daemon/lociighostd/__init__.py`.
    static let expectedDaemonVersion = "1.2.0"

    /// Pick the right starting coordinate for a new navigation. Order:
    /// 1. Currently simulated location (chain another route on top).
    /// 2. Mac proxy location (≈ iPhone real GPS).
    private func navigationOrigin() -> Coordinate? {
        if let sim = simulatedLocation { return sim }
        if let mac = macLocation.coordinate {
            return Coordinate(lat: mac.latitude, lng: mac.longitude)
        }
        return nil
    }

    // ------------------------------------------------------------------
    // Route preview
    // ------------------------------------------------------------------

    /// Rebuild `previewRoute` to match the current pendingStops + mode.
    ///
    /// * Straight-line mode: instant local compute (origin + stops as
    ///   the polyline). No daemon call.
    /// * Road mode: debounced OSRM lookup via `routing.route`. The
    ///   debounce keeps us from hitting the public OSRM server on every
    ///   keystroke / click while the user is still placing pins.
    func schedulePreviewRefresh() {
        previewTask?.cancel()

        if pendingStops.isEmpty {
            previewRoute = []
            return
        }

        if useStraightLine {
            // Local compute — no network. Show immediately.
            previewIsStraightLine = true
            if let origin = navigationOrigin() {
                previewRoute = [origin] + pendingStops
            } else {
                previewRoute = pendingStops
            }
            return
        }

        // Road mode — defer to the daemon, debounced.
        let stopsSnapshot = pendingStops
        let originSnapshot = navigationOrigin()
        let profile = travelProfile
        previewTask = Task { @MainActor [weak self] in
            try? await Task.sleep(for: .milliseconds(400))
            if Task.isCancelled { return }
            await self?.fetchPreviewViaOSRM(stops: stopsSnapshot,
                                            origin: originSnapshot,
                                            profile: profile)
        }
    }

    private func fetchPreviewViaOSRM(stops: [Coordinate],
                                     origin: Coordinate?,
                                     profile: TravelProfile) async {
        guard let client else { return }
        let waypoints: [Coordinate] = origin.map { [$0] + stops } ?? stops
        guard waypoints.count >= 2 else {
            previewRoute = []
            return
        }
        let stopsParam: [AnyCodable] = waypoints.map { c in
            AnyCodable(["lat": AnyCodable(c.lat), "lng": AnyCodable(c.lng)])
        }

        struct Reply: Decodable {
            struct Coord: Decodable { let lat: Double; let lng: Double }
            let coordinates: [Coord]
        }
        do {
            let reply: Reply = try await client.call("routing.route", params: [
                "stops":   AnyCodable(stopsParam),
                "profile": AnyCodable(profile.rawValue),
            ])
            // Avoid stomping on a more recent preview if the user has
            // already changed the inputs while we were awaiting OSRM.
            guard pendingStops == stops, !useStraightLine else { return }
            previewRoute = reply.coordinates.map { Coordinate(lat: $0.lat, lng: $0.lng) }
            previewIsStraightLine = false
        } catch {
            // Don't surface OSRM failures here -- the preview is best-
            // effort and it's noisy to flash an error every keystroke.
            // The next Navigate click will surface anything important.
        }
    }

    func restore(udid: String) async {
        guard let client else { return }
        do {
            _ = try await client.callRaw("location.restore", params: ["udid": AnyCodable(udid)])
            simulatedLocation = nil
            navigation = nil
            // Real GPS resumed -- the previous trip is over, drop its
            // route + destination from the map.
            activeRoute = nil
            activeDestination = nil
            activeRouteIsStraightLine = false

            // Phone is back on real GPS. We can't read iPhone GPS over DVT,
            // but the Mac's location is a sensible stand-in. Fly there now
            // using whatever fix we already have, and ask CoreLocation for
            // a fresh one in the background — when that lands the user can
            // tap the quick-recenter button to update.
            if let mac = macLocation.coordinate {
                pendingMapFly = MapFlyRequest(
                    coordinate: Coordinate(lat: mac.latitude, lng: mac.longitude),
                    spanMeters: 2_000
                )
            }
            macLocation.refresh()
        } catch {
            lastError = String(describing: error)
        }
    }

    // MARK: - Event loop

    private func startEventLoop(client: DaemonClient) {
        eventTask = Task { [weak self] in
            for await event in client.events {
                guard let self else { return }
                await self.handleEvent(event)
            }
        }
    }

    private func handleEvent(_ event: RPCEvent) async {
        switch event.method {
        case "event.device_changed":
            await refreshDevices()
        case "event.position_update":
            applyPositionEvent(event.params)
        case "event.state_changed":
            applyStateEvent(event.params)
        case "event.wifi_pair_progress":
            applyPairProgressEvent(event.params)
        default:
            break
        }
    }

    /// Map daemon-emitted `event.wifi_pair_progress` payloads to the
    /// observable `pairProgress` state. Stages map to a percentage so
    /// the GUI can render a smooth ProgressView; "done"/"failed" clear
    /// to nil so the spinner button reverts to its idle label.
    private func applyPairProgressEvent(_ params: [String: AnyCodable]) {
        let stage = stringValue(params["stage"]) ?? ""
        let message = stringValue(params["message"]) ?? ""
        switch stage {
        case "done", "failed":
            pairProgress = nil
        case "":
            return
        default:
            pairProgress = PairProgress(stage: stage, message: message)
        }
    }

    private func applyPositionEvent(_ params: [String: AnyCodable]) {
        guard let lat = doubleValue(params["lat"]),
              let lng = doubleValue(params["lng"])
        else { return }
        let coord = Coordinate(lat: lat, lng: lng)
        simulatedLocation = coord

        if var nav = navigation {
            nav.currentLocation = coord
            if let cum = doubleValue(params["cumulative_m"]),
               nav.distanceM > 0 {
                nav.progress = max(0, min(1, cum / nav.distanceM))
            }
            if let eta = doubleValue(params["eta_s"]) {
                nav.etaSeconds = eta
            }
            navigation = nav
        }
        if var rw = randomWalk {
            rw.current = coord
            if let s = doubleValue(params["speed_mps"]) { rw.speedMps = s }
            if let d = doubleValue(params["distance_traveled_m"]) { rw.distanceTraveledM = d }
            if let path = coordinateArray(params["planned_path"]) {
                rw.plannedPath = path
            }
            randomWalk = rw
        }
        if var js = joystick {
            js.current = coord
            if let h = doubleValue(params["heading_deg"]) { js.headingDeg = h }
            if let s = doubleValue(params["speed_mps"]) {
                js.speedMps = s
                js.isMoving = s > 0
            }
            joystick = js
        }
    }

    /// Decode a `[{"lat": Double, "lng": Double}, ...]` blob coming back
    /// over JSON-RPC. Returns nil if the wrapped value isn't an array.
    private func coordinateArray(_ wrapped: AnyCodable?) -> [Coordinate]? {
        guard let arr = wrapped?.value as? [AnyCodable] else { return nil }
        var out: [Coordinate] = []
        out.reserveCapacity(arr.count)
        for item in arr {
            guard let dict = item.value as? [String: AnyCodable] else { continue }
            guard let lat = doubleValue(dict["lat"]),
                  let lng = doubleValue(dict["lng"]) else { continue }
            out.append(Coordinate(lat: lat, lng: lng))
        }
        return out
    }

    private func applyStateEvent(_ params: [String: AnyCodable]) {
        // Random walk state events also flow through here. They carry a
        // refreshed planned_path roughly every five minutes, so the map
        // can redraw the upcoming polyline as the walker rolls forward.
        if var rw = randomWalk {
            if let path = coordinateArray(params["planned_path"]) {
                rw.plannedPath = path
                randomWalk = rw
            }
            if let s = stringValue(params["state"]), s == "stopped" {
                randomWalk = nil
            }
        }

        guard let stateRaw = stringValue(params["state"]) else { return }
        let mapped: NavigationVM.State?
        switch stateRaw {
        case "moving":  mapped = .moving
        case "paused":  mapped = .paused
        case "idle":    mapped = nil          // navigation is over
        case "stopped": mapped = nil
        default:        mapped = nil
        }
        if let mapped {
            if var nav = navigation {
                nav.state = mapped
                navigation = nav
            }
        } else {
            navigation = nil
        }
    }

    private func doubleValue(_ wrapped: AnyCodable?) -> Double? {
        guard let wrapped else { return nil }
        if let d = wrapped.value as? Double { return d }
        if let i = wrapped.value as? Int { return Double(i) }
        return nil
    }

    private func stringValue(_ wrapped: AnyCodable?) -> String? {
        guard let wrapped else { return nil }
        return wrapped.value as? String
    }

    // MARK: - Helpers

    private static func waitForSocket(path: String, timeout: TimeInterval) async -> Bool {
        let deadline = Date().addingTimeInterval(timeout)
        while Date() < deadline {
            if FileManager.default.fileExists(atPath: path) {
                return true
            }
            try? await Task.sleep(for: .milliseconds(100))
        }
        return false
    }
}

/// One row of `wifi.discover` output: an iPhone (or candidate IP) the
/// daemon found on the LAN. UDID is intentionally absent — we don't
/// know which paired device is at this IP until `wifi.connect_ip`
/// runs the pair-verify candidate sweep on the daemon side.
/// Mirrors the daemon's `/api/phone/info` response. The PIN is
/// regenerated on every daemon launch (and on demand via
/// `rotatePhoneControlPIN`), so this struct is short-lived and not
/// persisted across sessions.
struct PhoneControlInfo: Codable, Hashable, Sendable {
    let url: String
    let pin: String
    let lan_ip: String
    let port: Int
}

struct WiFiCandidate: Codable, Identifiable, Hashable, Sendable {
    let ip: String
    let port: Int
    let host: String
    let name: String
    /// "mdns" for Bonjour-discovered, "tcp_scan" for /24 fallback.
    let method: String

    var id: String { "\(ip):\(port)" }
}

/// Identifies which device the WiFi-connect selection sheet is open
/// for. `Identifiable` so the sheet can be presented via SwiftUI's
/// `.sheet(item:content:)` modifier — that pattern auto-handles the
/// "set to nil to dismiss" lifecycle without extra state plumbing.
struct WiFiConnectSheetTarget: Identifiable, Hashable, Sendable {
    let udid: String
    var id: String { udid }
}

/// Two-stage pairing progress fed by `event.wifi_pair_progress`. The
/// stage strings come straight from the daemon and are stable enough
/// to switch on for UI labels / fractions.
struct PairProgress: Hashable, Sendable {
    let stage: String
    let message: String

    /// 0.0–1.0 for ProgressView. Stages map to round numbers so the
    /// bar moves monotonically.
    var fraction: Double {
        switch stage {
        case "usbmux_query":   return 0.10
        case "usb_pairing":    return 0.30
        case "tunnel_setup":   return 0.55
        case "remote_pairing": return 0.80
        default:               return 0.50
        }
    }
}

/// Decoded `DeviceInfo` from `device.list`. Mirrors the daemon's
/// `models.DeviceInfo` shape.
struct DeviceVM: Codable, Identifiable, Hashable, Sendable {
    let udid: String
    let name: String
    let ios_version: String
    let transport: String
    let connected: Bool
    let developer_mode: Bool?    // nil == unknown / not queryable
    /// Every transport usbmuxd currently sees this UDID on. Always
    /// contains the active `transport`. May be empty for legacy
    /// daemons that don't yet report this field.
    let transports: [String]?
    /// True if `~/.pymobiledevice3/remote_<UDID>.plist` exists — i.e.
    /// the M-style WiFi pairing ritual has already run for this device
    /// and the GUI should hide / soften its "Pair for WiFi" button.
    /// nil for legacy daemons (< v0.2.9) that don't yet report it.
    let wifi_paired: Bool?
    /// When connected via WiFi (direct-IP RemotePairing), the peer
    /// endpoint the tunnel goes to. Lets the GUI's WiFi-Devices
    /// candidate list know exactly which row to flip into "Connected"
    /// state instead of all rows lighting up. nil for USB sessions
    /// or legacy daemons (< v0.2.10).
    let peer_ip: String?
    let peer_port: Int?

    var id: String { udid }
    var iosVersion: String { ios_version }
    var isUSB: Bool { transport == "usb" }
    /// True only if we know for certain dev mode is OFF. nil → don't show
    /// the warning, since some unpaired devices report nil even when on.
    var developerModeNeedsAttention: Bool { developer_mode == false }

    var availableTransports: Set<String> {
        Set(transports ?? [transport])
    }
    var supportsUSB: Bool { availableTransports.contains("usb") }
    var supportsWiFi: Bool { availableTransports.contains("network") }
    /// Convenience: the pair record exists on disk. Daemons older than
    /// v0.2.9 don't send this field; we return false in that case so
    /// the button stays visible.
    var isWiFiPaired: Bool { wifi_paired ?? false }

    /// Short label for the device's dev-mode state. Tri-state because an
    /// unpaired/untrusted device can return nil even when dev mode is on.
    /// Uses `String(localized:bundle:)` so the label tracks the user's
    /// language picker — the bundle reference is necessary because
    /// Bundle.module isn't visible from extensions in the LociiGhost
    /// executable target without going through .module explicitly.
    var developerModeLabel: String {
        switch developer_mode {
        case .some(true):
            return String(localized: "Dev Mode: ON", bundle: .module,
                          comment: "Device chip label — Developer Mode is enabled")
        case .some(false):
            return String(localized: "Dev Mode: OFF", bundle: .module,
                          comment: "Device chip label — Developer Mode is disabled")
        case .none:
            return String(localized: "Dev Mode: unknown", bundle: .module,
                          comment: "Device chip label — couldn't query Developer Mode state")
        }
    }
}

struct Coordinate: Hashable, Sendable {
    let lat: Double
    let lng: Double
}

struct MapFlyRequest: Hashable, Sendable {
    let id: UUID = UUID()
    let coordinate: Coordinate
    /// Side length of the displayed region in meters. Smaller = more
    /// zoomed in.
    let spanMeters: Double
}

/// Travel profile presets. Backend mirrors these in `routing.PROFILES`
/// and `handlers.SPEED_PRESETS`.
enum TravelProfile: String, CaseIterable, Identifiable, Sendable {
    case walking, cycling, driving

    var id: String { rawValue }

    /// Plain-String label for places that need a `String` (e.g. log
    /// lines, accessibility values). Resolves against `Locale.current`
    /// at call time. UI surfaces should prefer `labelKey` instead so
    /// the rendered Text follows the env locale (and therefore the
    /// language picker) on every state change.
    var label: String {
        switch self {
        case .walking:
            return String(localized: "Walking", bundle: .module,
                          comment: "Travel profile name")
        case .cycling:
            return String(localized: "Cycling", bundle: .module,
                          comment: "Travel profile name")
        case .driving:
            return String(localized: "Driving", bundle: .module,
                          comment: "Travel profile name")
        }
    }

    /// `LocalizedStringKey` flavour for use inside SwiftUI `Label(...)`,
    /// `Picker(...)` items, etc. Unlike the `String` `label` accessor,
    /// this one is re-evaluated by SwiftUI against the active env
    /// locale on every render, so flipping the language picker
    /// updates segmented-control labels live.
    var labelKey: LocalizedStringKey {
        switch self {
        case .walking: return "Walking"
        case .cycling: return "Cycling"
        case .driving: return "Driving"
        }
    }

    var symbol: String {
        switch self {
        case .walking: return "figure.walk"
        case .cycling: return "bicycle"
        case .driving: return "car.fill"
        }
    }

    /// m/s — must match the daemon's `SPEED_PRESETS`.
    var defaultSpeedMps: Double {
        switch self {
        case .walking: return 1.4    // ~5 km/h
        case .cycling: return 5.5    // ~20 km/h
        case .driving: return 11.1   // ~40 km/h
        }
    }

    var defaultSpeedKmh: Double { defaultSpeedMps * 3.6 }
}

struct NavigationVM: Sendable, Equatable {
    enum State: Sendable, Equatable { case moving, paused }

    var state: State
    var profile: TravelProfile
    var speedMps: Double
    var routeCoordinates: [Coordinate]
    var distanceM: Double
    var etaSeconds: Double
    var currentLocation: Coordinate
    var progress: Double            // 0...1
    var laps: Int = 1               // 1 = single trip, 2+ = looped

    var isPaused: Bool { state == .paused }
    /// Distance of one lap of the closed-loop route (or the full route
    /// when laps == 1). Used by the BottomBar to render a "Lap 2 / 5"
    /// badge instead of just a single accumulating progress bar.
    var lapDistanceM: Double { laps > 0 ? distanceM / Double(laps) : distanceM }
    /// Currently-walking lap, 1-indexed. Stays at 1 for single trips.
    var currentLap: Int {
        guard laps > 1, lapDistanceM > 0 else { return 1 }
        let traveled = distanceM * progress
        return min(laps, Int(traveled / lapDistanceM) + 1)
    }
}

struct RandomWalkVM: Sendable, Equatable {
    var center: Coordinate
    var radiusM: Double
    var current: Coordinate
    var speedMps: Double
    var distanceTraveledM: Double
    var isMoving: Bool
    /// Pre-generated upcoming targets that the daemon will walk through
    /// in order. The map renders this as a dashed polyline so the user
    /// sees what the iPhone will do over the next ~5 minutes.
    var plannedPath: [Coordinate] = []
}

struct JoystickVM: Sendable, Equatable {
    var current: Coordinate
    var headingDeg: Double
    var speedMps: Double
    var isMoving: Bool
}
