#!/usr/bin/env bash
# Build a Developer-ID-signed + notarised + stapled .dmg from an
# already-signed-and-stapled .app. Output: dist/LociiGhost-vX.Y.Z.dmg
#
# Usage:
#   ./Scripts/make-dmg.sh /path/to/LociiGhost.app
#
# Env vars (same as package-app.sh):
#   LOCIIGHOST_SIGN_IDENTITY  — Developer ID Application: ... (required)
#   LOCIIGHOST_NOTARY_PROFILE — notarytool keychain profile (required for
#                                full release; sign-only if absent)
#
# The DMG holds at its root:
#   1. LociiGhost.app
#   2. Applications  → /Applications  (symlink for the drag-install UX)
#   3. .background/  (hidden) — Finder window background PNG
#
# When the user double-clicks the DMG, Finder opens a 540×380 window
# with no toolbar / status bar, white background with a sage arrow
# pointing from the .app icon (left, 128 pt) to the Applications
# shortcut (right, 128 pt). The Finder view options are committed
# to the DMG's .DS_Store during a brief read-write phase, then the
# DMG is converted to compressed read-only for shipping.
#
# Background source: Scripts/dmg-assets/background.png (1080×760,
# auto-regenerated by `swift Scripts/generate-dmg-background.swift`
# if missing).

set -euo pipefail

APP="${1:-}"
if [[ -z "$APP" || ! -d "$APP" ]]; then
    echo "usage: $0 /path/to/LociiGhost.app" >&2
    exit 1
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIST="$ROOT/dist"

# Read CFBundleShortVersionString so the DMG filename embeds the
# version the user will actually see in About / Finder Get Info.
VERSION="$(plutil -extract CFBundleShortVersionString raw \
    "$APP/Contents/Info.plist")"
DMG="$DIST/LociiGhost-v$VERSION.dmg"

SIGN_IDENTITY="${LOCIIGHOST_SIGN_IDENTITY:-}"
NOTARY_PROFILE="${LOCIIGHOST_NOTARY_PROFILE:-}"

# Stage everything outside ~/Documents — same File Provider xattr
# minefield as package-app.sh. /tmp isn't watched by iCloud Drive
# and hdiutil happily reads from it.
STAGE_DIR="$(mktemp -d)"
STAGE="$STAGE_DIR/dmg-root"
mkdir -p "$STAGE"

# ditto copies content only (no xattrs / ACLs / resource forks); the
# .app's existing code signature survives intact, but the iCloud
# File Provider metadata does not follow into /tmp.
ditto --norsrc --noextattr --noacl "$APP" "$STAGE/$(basename "$APP")"

# Drag-target symlink. Finder shows it as "Applications" with the
# standard folder icon; clicking through it lands in /Applications.
ln -s /Applications "$STAGE/Applications"

# Background image for the Finder window. We stage it at
# `background/background.png` (no dot prefix during the
# AppleScript-driven layout pass — Finder's `file` reference under
# `tell disk` fails with -10006 when the folder is dot-hidden) and
# rename to `.background/` after the layout commits, before the
# read-write DMG is converted to read-only. Regenerate the PNG if
# it's missing so a clean clone can build the DMG without hunting
# for the file.
BG_SRC="$ROOT/Scripts/dmg-assets/background.png"
if [[ ! -f "$BG_SRC" ]]; then
    echo "==> background.png missing; regenerating"
    swift "$ROOT/Scripts/generate-dmg-background.swift"
fi
# Folder name deliberately avoids the word "background" — AppleScript's
# `background picture` property is one half of that bigram and Finder's
# parser will happily resolve "folder background" inside the same
# statement, triggering -10006 ("can't set folder to file"). `.dmg-bg`
# sidesteps the ambiguity entirely.
mkdir -p "$STAGE/.dmg-bg"
cp "$BG_SRC" "$STAGE/.dmg-bg/bg.png"

# Build, sign, notarise, and staple the DMG entirely under /tmp.
# Same File Provider gotcha as package-app.sh: if the DMG sits in
# ~/Documents/LociiGhost/dist/ during sign/staple, iCloud Drive can
# re-attach `com.apple.fileprovider.fpfs#P` between steps and break
# codesign mid-flight. Only the final stapled DMG moves into dist/.
TMP_DMG="$STAGE_DIR/$(basename "$DMG")"
RW_DMG="$STAGE_DIR/LociiGhost-rw.dmg"

# Step 1: build a read-write DMG large enough to hold the .app plus
# the .background PNG plus some Finder-side .DS_Store slack. The
# read-write phase exists only so the AppleScript layout block below
# can set the Finder window's view options — those settings live in
# the DMG's .DS_Store, which the OS only writes to a mounted volume.
# Detach any leftover /Volumes/LociiGhost* mount from a previous
# build OR from someone double-mounting the shipped DMG. macOS will
# happily mount a second copy of the same volume under "/Volumes/
# LociiGhost 1" / " 2" etc. — but `tell disk "LociiGhost"` in the
# AppleScript below resolves to the FIRST such disk, which is the
# read-only leftover, so the layout writes go to a frozen volume and
# `.DS_Store` never lands on our fresh read-write disk. This bit us
# between v1.10.6 and v1.10.7's first attempt.
for vol in /Volumes/LociiGhost /Volumes/LociiGhost\ [0-9]* ; do
    [[ -d "$vol" ]] || continue
    echo "==> detaching leftover mount $vol"
    hdiutil detach "$vol" -force >/dev/null 2>&1 || true
done

echo "==> building read-write DMG (for Finder layout pass)"
APP_SIZE_MB="$(du -sm "$APP" | awk '{print $1}')"
RW_SIZE_MB=$((APP_SIZE_MB + 50))
hdiutil create \
    -volname "LociiGhost" \
    -srcfolder "$STAGE" \
    -ov \
    -format UDRW \
    -size "${RW_SIZE_MB}m" \
    -o "$RW_DMG" >/dev/null

# Step 2: mount it (no Finder open / no auto-verify so the script
# stays in control), then drive Finder via AppleScript to configure
# the icon view layout — window size, hidden toolbar, icon
# positions, background image. Two sleeps bracket the osascript
# because Finder is famously timing-sensitive about when it actually
# notices a new mount and when it commits .DS_Store back to disk.
echo "==> mounting read-write DMG"
MOUNT_OUT="$(hdiutil attach "$RW_DMG" -nobrowse -noverify -noautoopen)"
MOUNT_DIR="$(echo "$MOUNT_OUT" | grep '/Volumes/' | awk '{for(i=3;i<=NF;i++) printf "%s%s", $i, (i<NF?OFS:ORS)}' | sed 's/[[:space:]]*$//')"
if [[ -z "$MOUNT_DIR" ]]; then
    echo "    failed to determine mount point" >&2
    echo "$MOUNT_OUT" >&2
    exit 1
fi
sleep 2

echo "==> applying Finder layout via AppleScript"
# Pass the real mount path in so the AppleScript can use a POSIX
# absolute reference for the background picture. macOS Sonoma+ Finder
# rejects the older `file "Disk:.dmg-bg:bg.png"` style with -10006
# ("can't set file X of disk Y to file X of disk Y") because the
# right-hand `file "..."` resolves to a Finder file object that
# evaluates equal to the property's current value before assignment.
# POSIX file via the actual mounted path avoids the ambiguity.
#
# Generous `delay` calls scattered through the block — Finder commits
# window state (bounds, view options, icon positions) to .DS_Store
# asynchronously, and on macOS Sonoma+ the previous tight script
# (delay 1 after update) routinely lost the bounds setting: the DMG
# opened at whatever size Finder felt like, ignoring the 540×380 we
# asked for. Structuring with `tell container window` blocks and
# multi-second delays after each significant write reliably gets
# the layout into .DS_Store before unmount.
#
# Capture osascript output explicitly so a silent Finder-automation
# permission denial (macOS TCC reset, version mismatch, etc.) doesn't
# produce a layout-less DMG with no warning — that bit us once
# between v1.10.6 and v1.10.7. `osascript` exit code is checked
# below, and `.DS_Store` presence is verified before unmount.
BG_POSIX="$MOUNT_DIR/.dmg-bg/bg.png"
OSA_OUT="$(osascript 2>&1 <<APPLESCRIPT
tell application "Finder"
    tell disk "LociiGhost"
        open
        delay 2
        tell container window
            set toolbar visible to false
            set statusbar visible to false
            set current view to icon view
            set the bounds to {400, 100, 940, 480}
        end tell
        delay 2
        set viewOptions to the icon view options of container window
        tell viewOptions
            set arrangement to not arranged
            set icon size to 128
        end tell
        set background picture of viewOptions to (POSIX file "$BG_POSIX") as alias
        delay 1
        set position of item "LociiGhost.app" of container window to {140, 140}
        set position of item "Applications" of container window to {400, 140}
        delay 1
        update without registering applications
        delay 5
        close
        delay 2
        -- Second open/close cycle. macOS Finder routinely "forgets"
        -- the bounds from the first pass — opening, re-asserting,
        -- and closing the window a second time forces the
        -- .DS_Store record onto disk reliably.
        open
        delay 2
        tell container window
            set toolbar visible to false
            set statusbar visible to false
            set current view to icon view
            set the bounds to {400, 100, 940, 480}
        end tell
        delay 2
        update without registering applications
        delay 5
        close
    end tell
end tell
APPLESCRIPT
)" || OSA_RC=$?
if [[ -n "${OSA_RC:-}" && "$OSA_RC" -ne 0 ]]; then
    echo "    ❌ osascript exited $OSA_RC" >&2
    echo "$OSA_OUT" >&2
    echo "    Likely cause: Finder Automation permission denied." >&2
    echo "    Fix: System Settings → Privacy & Security → Automation, allow this terminal to control Finder." >&2
    exit 1
fi
if [[ -n "$OSA_OUT" ]]; then
    echo "    osascript output:"
    printf '    %s\n' "$OSA_OUT"
fi
sleep 3
sync

# Verify the .DS_Store actually got written. If it didn't, the DMG
# will mount as a plain folder window — no background image, no
# arranged icons — which defeats the whole layout pass. Silently
# happened in one v1.10.7 build; from now on we fail loud.
if [[ ! -f "$MOUNT_DIR/.DS_Store" ]]; then
    echo "    ❌ .DS_Store missing from mount after AppleScript pass." >&2
    echo "    The DMG would ship without the Finder layout." >&2
    echo "    Try: macOS Settings → Privacy & Security → Automation," >&2
    echo "    grant Terminal (or whichever shell is running this) Finder access." >&2
    hdiutil detach "$MOUNT_DIR" -force >/dev/null 2>&1 || true
    exit 1
fi
echo "    .DS_Store present ($(stat -f%z "$MOUNT_DIR/.DS_Store") bytes)"

echo "==> unmounting"
# `-force` fallback in case Finder is still holding a reference.
hdiutil detach "$MOUNT_DIR" -quiet 2>/dev/null \
    || hdiutil detach "$MOUNT_DIR" -force

# Step 3: convert the read-write DMG to compressed read-only (UDZO).
# This is the final on-disk format we ship — smaller, immutable,
# fast to mount. The .DS_Store with the Finder layout carries over.
echo "==> converting to compressed read-only (UDZO)"
hdiutil convert "$RW_DMG" -format UDZO -o "$TMP_DMG" -ov >/dev/null
rm -f "$RW_DMG"

if [[ -n "$SIGN_IDENTITY" ]]; then
    echo "==> signing DMG: $SIGN_IDENTITY"
    codesign --force --sign "$SIGN_IDENTITY" --timestamp "$TMP_DMG"
    codesign --verify --verbose=2 "$TMP_DMG"
fi

if [[ -n "$SIGN_IDENTITY" && -n "$NOTARY_PROFILE" ]]; then
    echo "==> notarising DMG via keychain profile: $NOTARY_PROFILE"
    xcrun notarytool submit "$TMP_DMG" \
        --keychain-profile "$NOTARY_PROFILE" \
        --wait \
        | tee "$DIST/notarytool-dmg.log"

    echo "==> stapling notarisation ticket to DMG"
    xcrun stapler staple "$TMP_DMG"

    echo "==> post-staple Gatekeeper check"
    # `--type install` because we're verifying a DMG, not an .app.
    spctl --assess --type install --verbose "$TMP_DMG" 2>&1 \
        | sed 's/^/    /' || true

    echo "==> DMG notarised + stapled"
elif [[ -n "$SIGN_IDENTITY" ]]; then
    echo "==> DMG signed (no notary profile — local-only)"
else
    echo "==> DMG built (unsigned — for local testing only)"
fi

# Move the finished DMG into dist/ at the very end. By this point
# the DMG already has its notarisation ticket stapled inside, so any
# xattrs iCloud attaches afterwards don't affect Gatekeeper.
rm -f "$DMG"
mv "$TMP_DMG" "$DMG"
rm -rf "$STAGE_DIR"

# Quick size summary for the user.
ls -lh "$DMG" | awk '{print "==> size: " $5}'
